apiVersion: v1
kind: Service
metadata:
  name: github-webhook
  namespace: workspaces-system
spec:
  selector:
    app: github-webhook
  ports:
    - name: http
      port: 8080
      targetPort: 8080

