apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/workspaces.platform.dev_desktops.yaml
  - crds/workspaces.platform.dev_agentjobs.yaml
  - crds/workspaces.platform.dev_hometemplates.yaml
  - crds/workspaces.platform.dev_networkgrants.yaml
  - namespaces/desktops.yaml
  - namespaces/agents.yaml
  - operator
  - broker
  - egress-proxy
  - policies/agents-default-deny.yaml
  - policies/agents-allow-internal-proxies.yaml
