apiVersion: v1
kind: LimitRange
metadata:
  name: desktops-default-limits
  namespace: desktops
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "1"
        memory: "2Gi"
      default:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: desktops-quota
  namespace: desktops
spec:
  hard:
    pods: "50"
    persistentvolumeclaims: "100"
    requests.storage: "5Ti"
    requests.cpu: "64"
    requests.memory: "128Gi"
    limits.cpu: "128"
    limits.memory: "256Gi"

