//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand for MVP; replace with controller-gen when the API settles.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Desktop) DeepCopyInto(out *Desktop) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	out.Spec = in.Spec
	if in.Spec.SSH.AuthorizedKeys != nil {
		out.Spec.SSH.AuthorizedKeys = append([]string(nil), in.Spec.SSH.AuthorizedKeys...)
	}
	if in.Spec.NodeSelector != nil {
		out.Spec.NodeSelector = make(map[string]string, len(in.Spec.NodeSelector))
		for k, v := range in.Spec.NodeSelector {
			out.Spec.NodeSelector[k] = v
		}
	}
	if in.Spec.Tolerations != nil {
		out.Spec.Tolerations = append(out.Spec.Tolerations[:0:0], in.Spec.Tolerations...)
	}
	if in.Spec.Home.StorageClassName != nil {
		v := *in.Spec.Home.StorageClassName
		out.Spec.Home.StorageClassName = &v
	}
	out.Spec.Resources = *in.Spec.Resources.DeepCopy()

	out.Status = in.Status
	if in.Status.Conditions != nil {
		out.Status.Conditions = append(out.Status.Conditions[:0:0], in.Status.Conditions...)
	}
}

func (in *Desktop) DeepCopy() *Desktop {
	if in == nil {
		return nil
	}
	out := new(Desktop)
	in.DeepCopyInto(out)
	return out
}

func (in *Desktop) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DesktopList) DeepCopyInto(out *DesktopList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Desktop, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *DesktopList) DeepCopy() *DesktopList {
	if in == nil {
		return nil
	}
	out := new(DesktopList)
	in.DeepCopyInto(out)
	return out
}

func (in *DesktopList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentJob) DeepCopyInto(out *AgentJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	out.Spec = in.Spec
	if in.Spec.Command != nil {
		out.Spec.Command = append([]string(nil), in.Spec.Command...)
	}
	if in.Spec.Args != nil {
		out.Spec.Args = append([]string(nil), in.Spec.Args...)
	}
	if in.Spec.Env != nil {
		out.Spec.Env = append(out.Spec.Env[:0:0], in.Spec.Env...)
	}
	out.Spec.Resources = *in.Spec.Resources.DeepCopy()
	if in.Spec.NodeSelector != nil {
		out.Spec.NodeSelector = make(map[string]string, len(in.Spec.NodeSelector))
		for k, v := range in.Spec.NodeSelector {
			out.Spec.NodeSelector[k] = v
		}
	}
	if in.Spec.Tolerations != nil {
		out.Spec.Tolerations = append(out.Spec.Tolerations[:0:0], in.Spec.Tolerations...)
	}
	if in.Spec.RuntimeClassName != nil {
		v := *in.Spec.RuntimeClassName
		out.Spec.RuntimeClassName = &v
	}
	if in.Spec.TTLSecondsAfterFinished != nil {
		v := *in.Spec.TTLSecondsAfterFinished
		out.Spec.TTLSecondsAfterFinished = &v
	}

	out.Status = in.Status
	if in.Status.Conditions != nil {
		out.Status.Conditions = append(out.Status.Conditions[:0:0], in.Status.Conditions...)
	}
}

func (in *AgentJob) DeepCopy() *AgentJob {
	if in == nil {
		return nil
	}
	out := new(AgentJob)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentJobList) DeepCopyInto(out *AgentJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentJob, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentJobList) DeepCopy() *AgentJobList {
	if in == nil {
		return nil
	}
	out := new(AgentJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NetworkGrant) DeepCopyInto(out *NetworkGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	out.Spec = in.Spec
	in.Spec.PodSelector.DeepCopyInto(&out.Spec.PodSelector)
	if in.Spec.Egress != nil {
		out.Spec.Egress = make([]NetworkGrantEgressRule, len(in.Spec.Egress))
		for i := range in.Spec.Egress {
			out.Spec.Egress[i] = in.Spec.Egress[i]
			if in.Spec.Egress[i].Ports != nil {
				out.Spec.Egress[i].Ports = append([]int32(nil), in.Spec.Egress[i].Ports...)
			}
		}
	}

	out.Status = in.Status
	in.Status.ExpiresAt.DeepCopyInto(&out.Status.ExpiresAt)
	if in.Status.Conditions != nil {
		out.Status.Conditions = append(out.Status.Conditions[:0:0], in.Status.Conditions...)
	}
}

func (in *NetworkGrant) DeepCopy() *NetworkGrant {
	if in == nil {
		return nil
	}
	out := new(NetworkGrant)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NetworkGrantList) DeepCopyInto(out *NetworkGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NetworkGrant, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *NetworkGrantList) DeepCopy() *NetworkGrantList {
	if in == nil {
		return nil
	}
	out := new(NetworkGrantList)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
