apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nix-cache-attic.yaml
  - package-proxy-athens.yaml
  - package-proxy-cargo.yaml
  - package-proxy-devpi.yaml
  - package-proxy-maven.yaml
  - package-proxy-registry.yaml
  - package-proxy-verdaccio.yaml

